version: "3.4"

services:
  server:
    container_name: monster-shoot-server
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
      target: production
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
    networks:
      - monster-shoot-networks
    environment:
      NODE_ENV: production

networks:
  monster-shoot-networks:
    driver: bridge
